default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--config, .config/ruff.toml, --fix]
      # Run the formatter.
      - id: ruff-format
        args: [--config, .config/ruff.toml]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.15
    hooks:
      # Run the pip compile
      - id: pip-compile
        name: pip-compile requirements.txt
        files: pyproject.toml
        args: [ pyproject.toml, --resolver=backtracking, --all-extras, --upgrade, -q, -o, requirements.txt ]
